// Do not edit. This file is machine generated by the Resource DLL Wizard.

library BricxCC_18_49;

{ITE} {LCID:00000409:00000409} {}
{ITE} {DFMFileType} {CodeUnit.dfm}
{ITE} {RCFileType} {ToolbarBackground.rc}
{ITE} {RCFileType} {NXTSound.rc}
{ITE} {RCFileType} {VistaManifest.rc}
{ITE} {<unknown>} {macro_img.res}

{$R 'CodeUnit.dfm'}
{$R 'ToolbarBackground.res' 'ToolbarBackground.rc'}
{$R 'NXTSound.res' 'NXTSound.rc'}
{$R 'VistaManifest.res' 'VistaManifest.rc'}

{$E ENU}

begin
end.