// Do not edit. This file is machine generated by the Resource DLL Wizard.

library BricxCC;

{ITE} {LCID:00000409:00000409} {}
{ITE} {DFMFileType} {Controller.dfm}
{ITE} {DFMFileType} {MainUnit.dfm}
{ITE} {DFMFileType} {Diagnose.dfm}
{ITE} {DFMFileType} {Unlock.dfm}
{ITE} {DFMFileType} {Watch.dfm}
{ITE} {DFMFileType} {uNewWatch.dfm}
{ITE} {DFMFileType} {About.dfm}
{ITE} {DFMFileType} {GotoLine.dfm}
{ITE} {DFMFileType} {SearchRCX.dfm}
{ITE} {DFMFileType} {Piano.dfm}
{ITE} {DFMFileType} {Preferences.dfm}
{ITE} {DFMFileType} {Editor.dfm}
{ITE} {DFMFileType} {ConstructUnit.dfm}
{ITE} {DFMFileType} {JoystickUnit.dfm}
{ITE} {DFMFileType} {PuzzleUnit.dfm}
{ITE} {DFMFileType} {DatalogUnit.dfm}
{ITE} {DFMFileType} {MemoryUnit.dfm}
{ITE} {DFMFileType} {CodeUnit.dfm}
{ITE} {DFMFileType} {MessageUnit.dfm}
{ITE} {DFMFileType} {DPageSetup.dfm}
{ITE} {DFMFileType} {DTestPrintPreview.dfm}
{ITE} {DFMFileType} {RemoteUnit.dfm}
{ITE} {DFMFileType} {DataAnalysis.dfm}
{ITE} {DFMFileType} {uChartExport.dfm}
{ITE} {DFMFileType} {uChartConfig.dfm}
{ITE} {DFMFileType} {uSeriesConfig.dfm}
{ITE} {DFMFileType} {uPromptSeries.dfm}
{ITE} {DFMFileType} {EditCodeTemplate.dfm}
{ITE} {DFMFileType} {CodeTemplates.dfm}
{ITE} {DFMFileType} {uCodeExplorer.dfm}
{ITE} {DFMFileType} {Transfer.dfm}
{ITE} {DFMFileType} {Transdlg.dfm}
{ITE} {DFMFileType} {uExplorerOptions.dfm}
{ITE} {DFMFileType} {uMacroForm.dfm}
{ITE} {DFMFileType} {uMacroEditor.dfm}
{ITE} {DFMFileType} {uWindowList.dfm}
{ITE} {DFMFileType} {uExtensionDlg.dfm}
{ITE} {DFMFileType} {GX_ProcedureList.dfm}
{ITE} {DFMFileType} {uProjectManager.dfm}
{ITE} {DFMFileType} {uMIDIConversion.dfm}
{ITE} {DFMFileType} {uSetLNPAddress.dfm}
{ITE} {DFMFileType} {uForthConsole.dfm}
{ITE} {DFMFileType} {uSetValues.dfm}
{ITE} {DFMFileType} {uEEPROM.dfm}
{ITE} {DFMFileType} {uWav2RSO.dfm}
{ITE} {DFMFileType} {uNXTExplorer.dfm}
{ITE} {DFMFileType} {uNXTController.dfm}
{ITE} {DFMFileType} {uHEXViewer.dfm}
{ITE} {DFMFileType} {uNXTImage.dfm}
{ITE} {RCFileType} {ToolbarBackground.rc}
{ITE} {RCFileType} {NXTSound.rc}
{ITE} {RCFileType} {VistaManifest.rc}
{ITE} {<unknown>} {macro_img.res}

{$R 'Controller.dfm'}
{$R 'MainUnit.dfm'}
{$R 'Diagnose.dfm'}
{$R 'Unlock.dfm'}
{$R 'Watch.dfm'}
{$R 'uNewWatch.dfm'}
{$R 'About.dfm'}
{$R 'GotoLine.dfm'}
{$R 'SearchRCX.dfm'}
{$R 'Piano.dfm'}
{$R 'Preferences.dfm'}
{$R 'Editor.dfm'}
{$R 'ConstructUnit.dfm'}
{$R 'JoystickUnit.dfm'}
{$R 'PuzzleUnit.dfm'}
{$R 'DatalogUnit.dfm'}
{$R 'MemoryUnit.dfm'}
{$R 'CodeUnit.dfm'}
{$R 'MessageUnit.dfm'}
{$R 'DPageSetup.dfm'}
{$R 'DTestPrintPreview.dfm'}
{$R 'RemoteUnit.dfm'}
{$R 'DataAnalysis.dfm'}
{$R 'uChartExport.dfm'}
{$R 'uChartConfig.dfm'}
{$R 'uSeriesConfig.dfm'}
{$R 'uPromptSeries.dfm'}
{$R 'EditCodeTemplate.dfm'}
{$R 'CodeTemplates.dfm'}
{$R 'uCodeExplorer.dfm'}
{$R 'Transfer.dfm'}
{$R 'Transdlg.dfm'}
{$R 'uExplorerOptions.dfm'}
{$R 'uMacroForm.dfm'}
{$R 'uMacroEditor.dfm'}
{$R 'uWindowList.dfm'}
{$R 'uExtensionDlg.dfm'}
{$R 'GX_ProcedureList.dfm'}
{$R 'uProjectManager.dfm'}
{$R 'uMIDIConversion.dfm'}
{$R 'uSetLNPAddress.dfm'}
{$R 'uForthConsole.dfm'}
{$R 'uSetValues.dfm'}
{$R 'uEEPROM.dfm'}
{$R 'uWav2RSO.dfm'}
{$R 'uNXTExplorer.dfm'}
{$R 'uNXTController.dfm'}
{$R 'uHEXViewer.dfm'}
{$R 'uNXTImage.dfm'}
{$R 'ToolbarBackground.res' 'ToolbarBackground.rc'}
{$R 'NXTSound.res' 'NXTSound.rc'}
{$R 'VistaManifest.res' 'VistaManifest.rc'}

{$E ENU}

begin
end.