@echo off
lazres About.lrs About.lfm
lazres CodeTemplates.lrs CodeTemplates.lfm
lazres CodeUnit.lrs CodeUnit.lfm
lazres ConstructUnit.lrs ConstructUnit.lfm
lazres Controller.lrs Controller.lfm
lazres DataAnalysis.lrs DataAnalysis.lfm
lazres DatalogUnit.lrs DatalogUnit.lfm
lazres Diagnose.lrs Diagnose.lfm
lazres dlgConfirmReplace.lrs dlgConfirmReplace.lfm
lazres dlgReplaceText.lrs dlgReplaceText.lfm
lazres dlgSearchText.lrs dlgSearchText.lfm
lazres DPageSetup.lrs DPageSetup.lfm
lazres DTestPrintPreview.lrs DTestPrintPreview.lfm
lazres EditCodeTemplate.lrs EditCodeTemplate.lfm
lazres Editor.lrs Editor.lfm
lazres GotoLine.lrs GotoLine.lfm
lazres GX_ProcedureList.lrs GX_ProcedureList.lfm
lazres JoystickUnit.lrs JoystickUnit.lfm
lazres MainUnit.lrs MainUnit.lfm
lazres MemoryUnit.lrs MemoryUnit.lfm
lazres MessageUnit.lrs MessageUnit.lfm
lazres Piano.lrs Piano.lfm
lazres Preferences.lrs Preferences.lfm
lazres PuzzleUnit.lrs PuzzleUnit.lfm
lazres RemoteUnit.lrs RemoteUnit.lfm
lazres SearchRCX.lrs SearchRCX.lfm
lazres Transdlg.lrs Transdlg.lfm
lazres Transfer.lrs Transfer.lfm
lazres uChartConfig.lrs uChartConfig.lfm
lazres uChartExport.lrs uChartExport.lfm
lazres ucodeedit.lrs ucodeedit.lfm
lazres uCodeExplorer.lrs uCodeExplorer.lfm
lazres uCompStatus.lrs uCompStatus.lfm
lazres uEEAlignConfig.lrs uEEAlignConfig.lfm
lazres uEEAlignOpt.lrs uEEAlignOpt.lfm
lazres uEECommentConfig.lrs uEECommentConfig.lfm
lazres uEEPROM.lrs uEEPROM.lfm
lazres uExplorerOptions.lrs uExplorerOptions.lfm
lazres uExtensionDlg.lrs uExtensionDlg.lfm
lazres uForthConsole.lrs uForthConsole.lfm
lazres uFSTest.lrs uFSTest.lfm
lazres uHexViewer.lrs uHexViewer.lfm
lazres uMacroEditor.lrs uMacroEditor.lfm
lazres uMacroForm.lrs uMacroForm.lfm
lazres uMidiBatch.lrs uMidiBatch.lfm
lazres uMIDIConversion.lrs uMIDIConversion.lfm
lazres uNewWatch.lrs uNewWatch.lfm
lazres Unlock.lrs Unlock.lfm
lazres uNXTController.lrs uNXTController.lfm
lazres uNXTExplorer.lrs uNXTExplorer.lfm
lazres uNXTImage.lrs uNXTImage.lfm
lazres uNXTImagePrefs.lrs uNXTImagePrefs.lfm
lazres uNXTName.lrs uNXTName.lfm
lazres uPortPrompt.lrs uPortPrompt.lfm
lazres uportsedit.lrs uportsedit.lfm
lazres uProjectManager.lrs uProjectManager.lfm
lazres uRemoteProgMap.lrs uRemoteProgMap.lfm
lazres uRICLoader.lrs uRICLoader.lfm
lazres uRICView.lrs uRICView.lfm
lazres uRmdPlayer.lrs uRmdPlayer.lfm
lazres uRPGEditor.lrs uRPGEditor.lfm
lazres uSampleClient.lrs uSampleClient.lfm
lazres uScoutMem.lrs uScoutMem.lfm
lazres uSearchNXT.lrs uSearchNXT.lfm
lazres uSeriesConfig.lrs uSeriesConfig.lfm
lazres uSetLNPAddress.lrs uSetLNPAddress.lfm
lazres uSetValues.lrs uSetValues.lfm
lazres uToolPalette.lrs uToolPalette.lfm
lazres uWav2RSO.lrs uWav2RSO.lfm
lazres uWindowList.lrs uWindowList.lfm
lazres Watch.lrs Watch.lfm
