(*
 * The contents of this file are subject to the Mozilla Public License
 * Version 1.1 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS"
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
 * License for the specific language governing rights and limitations
 * under the License.
 *
 * The Initial Developer of this code is John Hansen.
 * Portions created by John Hansen are Copyright (C) 2009 John Hansen.
 * All Rights Reserved.
 *
 *)
unit uROPSCodeComp;

interface

uses
  uCppCode;

const
  ROPSUnitNamesSize = 5;
  ROPSUnitNames: array[0..ROPSUnitNamesSize-1] of string = (
    '',
    'brick_common',
    'uSpirit',
    'uGlobals',
    'rcx_constants'
  );

const
  ROPSCodeCompDataSize = 399;
  ROPSCodeCompData: array[0..ROPSCodeCompDataSize-1] of TCppCodeComp = (
    (Kind: ckKeyword; Name: 'and'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'array'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'as'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'begin'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'break'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'bytearray'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'case'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'chr'; Location: 0; Params: '(X : Byte)'; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'class'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'const'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'constructor'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'continue'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'destructor'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'div'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'do'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'downto'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'else'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'end'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'except'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'exit'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'external'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'finally'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'for'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'forward'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'function'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'goto'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'if'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'implementation'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'in'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'interface'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'is'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'label'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'mod'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'nil'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'not'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'of'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'or'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'ord'; Location: 0; Params: '(C : Char)'; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'private'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'procedure'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'program'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'property'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'protected'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'public'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'published'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'record'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'repeat'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'set'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'shl'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'shr'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'then'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'to'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'try'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'type'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'unit'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'until'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'uses'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'while'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'with'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckKeyword; Name: 'xor'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),

    (Kind: ckAPIType; Name: 'Boolean'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'Byte'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'Char'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'Double'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'Extended'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'Int64'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'Longint'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'Longword'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'Shortint'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'Single'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'Smallint'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'string'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'Variant'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'WideChar'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'WideString'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'Word'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),

    (Kind: ckAPIType; Name: 'TRect'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'TDateTime'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'TNotifyEvent'; Location: 0; Params: 'procedure (Sender: TObject)'; Count: 1; Alpha: atNumeric),

(*
  cl.AddConstantN('soFromBeginning', 'Longint').Value.ts32 := 0;
  cl.AddConstantN('soFromCurrent', 'Longint').Value.ts32 := 1;
  cl.AddConstantN('soFromEnd', 'Longint').Value.ts32 := 2;
  cl.AddConstantN('toEOF', 'Char').Value.tchar := #0;
  cl.AddConstantN('toSymbol', 'Char').Value.tchar := #1;
  cl.AddConstantN('toString', 'Char').Value.tchar := #2;
  cl.AddConstantN('toInteger', 'Char').Value.tchar := #3;
  cl.AddConstantN('toFloat', 'Char').Value.tchar := #4;
  cl.AddConstantN('fmCreate', 'Longint').Value.ts32 := $FFFF;
  cl.AddConstantN('fmOpenRead', 'Longint').Value.ts32 := 0;
  cl.AddConstantN('fmOpenWrite', 'Longint').Value.ts32 := 1;
  cl.AddConstantN('fmOpenReadWrite', 'Longint').Value.ts32 := 2;
  cl.AddConstantN('fmShareCompat', 'Longint').Value.ts32 := 0;
  cl.AddConstantN('fmShareExclusive', 'Longint').Value.ts32 := $10;
  cl.AddConstantN('fmShareDenyWrite', 'Longint').Value.ts32 := $20;
  cl.AddConstantN('fmShareDenyRead', 'Longint').Value.ts32 := $30;
  cl.AddConstantN('fmShareDenyNone', 'Longint').Value.ts32 := $40;
  cl.AddConstantN('SecsPerDay', 'Longint').Value.ts32 := 86400;
  cl.AddConstantN('MSecPerDay', 'Longint').Value.ts32 := 86400000;
  cl.AddConstantN('DateDelta', 'Longint').Value.ts32 := 693594;
  cl.AddTypeS('TAlignment', '(taLeftJustify, taRightJustify, taCenter)');
  cl.AddTypeS('THelpEvent', 'function (Command: Word; Data: Longint; var CallHelp: Boolean): Boolean');
  cl.AddTypeS('TGetStrProc', 'procedure(const S: string)');
  cl.AddTypeS('TDuplicates', '(dupIgnore, dupAccept, dupError)');
  cl.AddTypeS('TOperation', '(opInsert, opRemove)');
  cl.AddTypeS('THANDLE', 'Longint');

*)

    (Kind: ckAPIFunc; Name: 'IntToStr'; Location: 0; Params: '(I : Longint)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'StrToInt'; Location: 0; Params: '(const s : string)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'StrToIntDef'; Location: 0; Params: '(const s : string; Def: Longint)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'FloatToStr'; Location: 0; Params: '(E : Extended)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'StrToFloat'; Location: 0; Params: '(const s : string)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'EncodeDate'; Location: 0; Params: '(Year: Word; Month: Word; Day: Word)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'EncodeTime'; Location: 0; Params: '(Hour: Word; Min: Word; Sec: Word; MSec: Word)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'TryEncodeDate'; Location: 0; Params: '(Year: Word; Month: Word; Day: Word; var Date: TDateTime)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'TryEncodeTime'; Location: 0; Params: '(Hour: Word; Min: Word; Sec: Word; MSec: Word; var Time: TDateTime)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'DecodeDate'; Location: 0; Params: '(const DateTime: TDateTime; var Year: Word; var Month: Word; var Day: Word)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'DecodeTime'; Location: 0; Params: '(const DateTime: TDateTime; var Hour: Word; var Min: Word; var Sec: Word; var MSec: Word)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'DayOfWeek'; Location: 0; Params: '(const DateTime: TDateTime)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Date'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Time'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Now'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'DateTimeToUnix'; Location: 0; Params: '(D: TDateTime)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'UnixToDateTime'; Location: 0; Params: '(U: Int64)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'DateToStr'; Location: 0; Params: '(D: TDateTime)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'StrToDate'; Location: 0; Params: '(const s: string)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'FormatDateTime'; Location: 0; Params: '(const fmt: string; D: TDateTime)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Pos'; Location: 0; Params: '(Substr: string; S: string)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Copy'; Location: 0; Params: '(S: string; Index : Integer; Count : Integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Delete'; Location: 0; Params: '(var S: string; Index : Integer; Count : Integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Insert'; Location: 0; Params: '(Source: string; var S: string; Index : Integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'UpperCase'; Location: 0; Params: '(const S: string)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'LowerCase'; Location: 0; Params: '(const S: string)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Trim'; Location: 0; Params: '(const S: string)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Length'; Location: 0; Params: '(const S: string)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SetLength'; Location: 0; Params: '(var S: string; NewLength : Integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Low'; Location: 0; Params: '(X)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'High'; Location: 0; Params: '(X)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Dec'; Location: 0; Params: '(var X; N : LongInt = 1)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Inc'; Location: 0; Params: '(var X; N : LongInt = 1)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Sin'; Location: 0; Params: '(X: Extended)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Cos'; Location: 0; Params: '(X: Extended)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Sqrt'; Location: 0; Params: '(X: Extended)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Round'; Location: 0; Params: '(X: Extended)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Trunc'; Location: 0; Params: '(X: Extended)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Int'; Location: 0; Params: '(X: Extended)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Pi'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Abs'; Location: 0; Params: '(X)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Padl'; Location: 0; Params: '(s: string; i: Integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Padr'; Location: 0; Params: '(s: string; i: Integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Padz'; Location: 0; Params: '(s: string; i: Integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Replicate'; Location: 0; Params: '(Ch: Char; Count: Integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'StringOfChar'; Location: 0; Params: '(Ch: Char; Count: Integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Assigned'; Location: 0; Params: '(P)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Unassigned'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Null'; Location: 0; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'VarIsEmpty'; Location: 0; Params: '(const V: Variant)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'VarIsNull'; Location: 0; Params: '(const V: Variant)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'VarType'; Location: 0; Params: '(const V: Variant)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'GetArrayLength'; Location: 0; Params: '(A)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SetArrayLength'; Location: 0; Params: '(var A)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'AnsiUpperCase'; Location: 0; Params: '(const S: string)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'AnsiLowerCase'; Location: 0; Params: '(const S: string)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Int64ToStr'; Location: 0; Params: '(I : Int64)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'StrToInt64'; Location: 0; Params: '(const s : string)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SizeOf'; Location: 0; Params: '(X)'; Count: 1; Alpha: atNumeric),
(*
  RegisterFunctionName('RAISELASTEXCEPTION', DefPRoc, Pointer(30), nil);
  RegisterFunctionName('RAISEEXCEPTION', DefPRoc, Pointer(31), nil);
  RegisterFunctionName('EXCEPTIONTYPE', DefPRoc, Pointer(32), nil);
  RegisterFunctionName('EXCEPTIONPARAM', DefPRoc, Pointer(33), nil);
  RegisterFunctionName('EXCEPTIONPROC', DefPRoc, Pointer(34), nil);
  RegisterFunctionName('EXCEPTIONPOS', DefPRoc, Pointer(35), nil);
  RegisterFunctionName('EXCEPTIONTOSTRING', DefProc, Pointer(36), nil);
*)

    (Kind: ckAPIConst; Name: 'K_RCX'; Location: 3; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'K_CYBER'; Location: 3; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'K_SCOUT'; Location: 3; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'K_RCX2'; Location: 3; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'K_SPY'; Location: 3; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'K_NXT'; Location: 3; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'K_SPRO'; Location: 3; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'rtRCX'; Location: 3; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'rtCybermaster'; Location: 3; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'rtScout'; Location: 3; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'rtRCX2'; Location: 3; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'rtSpy'; Location: 3; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'rtNXT'; Location: 3; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'rtSPro'; Location: 3; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRemoteKeysReleased'; Location: 3; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRemotePBMessage1'; Location: 3; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRemotePBMessage2'; Location: 3; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRemotePBMessage3'; Location: 3; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRemoteOutAForward'; Location: 3; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRemoteOutBForward'; Location: 3; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRemoteOutCForward'; Location: 3; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRemoteOutABackward'; Location: 3; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRemoteOutBBackward'; Location: 3; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRemoteOutCBackward'; Location: 3; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRemoteSelProgram1'; Location: 3; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRemoteSelProgram2'; Location: 3; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRemoteSelProgram3'; Location: 3; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRemoteSelProgram4'; Location: 3; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRemoteSelProgram5'; Location: 3; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRemoteStopOutOff'; Location: 3; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRemotePlayASound'; Location: 3; Params: ''; Count: 1; Alpha: atNumeric),

    (Kind: ckAPIType; Name: 'TDownloadStatusEvent'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'TGetVarInfoByIDEvent'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'TGetVarInfoByNameEvent'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'NXTLSBlock'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'NXTMessage'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'NXTDataBuffer'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'EEPROMBlock'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'TNXTFileType'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'TTransmitLevel'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'TLSSource'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'TThresholdValue'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'TBlinkTimeValue'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'TTimerNumber'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'TCounterNumber'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'TTCSource'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'TScoutMotion'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'TScoutTouch'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'TScoutLight'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'TScoutScale'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'TScoutEffects'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'TSoundSetNumber'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'TGlobalOutAction'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'TGlobalDirAction'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'TMotorsNum'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),

    (Kind: ckAPIFunc; Name: 'BrickComm'; Location: 1; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'ReleaseBrickComm'; Location: 1; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'CreateInitFile'; Location: 1; Params: ''; Count: 1; Alpha: atNumeric),

    (Kind: ckAPIFunc; Name: 'NameToNXTFileType'; Location: 2; Params: '(name : string)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'MakeValidNXTFilename'; Location: 2; Params: '(const filename : string)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'GetInitFilename'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'FantomAPIAvailable'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'LoadNXTPorts'; Location: 2; Params: '(aStrings : TStrings)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'BytesToCardinal'; Location: 2; Params: '(b1 : byte; b2 : byte; b3 : byte; b4 : Byte)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'InstalledFirmwareAsString'; Location: 2; Params: '(const ifw : TInstalledFirmware)'; Count: 1; Alpha: atNumeric),

    (Kind: ckAPIFunc; Name: 'Open'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Close'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'PlayTone'; Location: 2; Params: '(aFreq: word; aTime : word)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'PlaySystemSound'; Location: 2; Params: '(aSnd : byte)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'MotorsOn'; Location: 2; Params: '(aMotorList : Byte)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'MotorsOff'; Location: 2; Params: '(aMotorList : Byte)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'MotorsFloat'; Location: 2; Params: '(aMotorList : Byte)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SetFwd'; Location: 2; Params: '(aMotorList : Byte)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SetRwd'; Location: 2; Params: '(aMotorList : Byte)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SwitchDirection'; Location: 2; Params: '(aMotorList : Byte)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SetMotorPower'; Location: 2; Params: '(aMotorList : Byte; aSrc: integer; aNum : integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SetSensorType'; Location: 2; Params: '(aNum: integer; aType : integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SetSensorMode'; Location: 2; Params: '(aNum: integer; aMode : integer; aSlope : integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'ClearSensorValue'; Location: 2; Params: '(aNum: integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'TowerExists'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Ping'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'PrepareBrick'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'UnlockFirmware'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'UnlockBrick'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'DownloadMemoryMap'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'MonitorIR'; Location: 2; Params: '(aSeconds: integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'PowerDownTime'; Location: 2; Params: '(aTime: integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'BatteryLevel'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'BrickAlive'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Shutdown'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Sleep'; Location: 2; Params: '(aVal: integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Version'; Location: 2; Params: '(var rom : Cardinal; var ram : Cardinal)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'TransmitPower'; Location: 2; Params: '(aLevel: TTransmitLevel)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Poll'; Location: 2; Params: '(aSrc: integer; aNum : integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'StartTask'; Location: 2; Params: '(aTask: integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'StopTask'; Location: 2; Params: '(aTask: integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'StopAllTasks'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'DeleteTask'; Location: 2; Params: '(aTask: integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'DeleteAllTasks'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'DeleteSub'; Location: 2; Params: '(aSub: integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'DeleteAllSubs'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'ClearTimer'; Location: 2; Params: '(aNum: integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'ClearMemory'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'GetOutputStatus'; Location: 2; Params: '(aOut: integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'GetVariableValue'; Location: 2; Params: '(aVar: integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'GetInputValue'; Location: 2; Params: '(aIn: integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'GetMessageValue'; Location: 2; Params: '(aNum: integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'GetTimerValue'; Location: 2; Params: '(aNum: integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'GetCounterValue'; Location: 2; Params: '(aNum: integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SetVar'; Location: 2; Params: '(aVar: integer; aSrc: integer; aNum : integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SumVar'; Location: 2; Params: '(aVar: integer; aSrc: integer; aNum : integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SubVar'; Location: 2; Params: '(aVar: integer; aSrc: integer; aNum : integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'DivVar'; Location: 2; Params: '(aVar: integer; aSrc: integer; aNum : integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'MulVar'; Location: 2; Params: '(aVar: integer; aSrc: integer; aNum : integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SgnVar'; Location: 2; Params: '(aVar: integer; aSrc: integer; aNum : integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'AbsVar'; Location: 2; Params: '(aVar: integer; aSrc: integer; aNum : integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'AndVar'; Location: 2; Params: '(aVar: integer; aSrc: integer; aNum : integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'OrVar'; Location: 2; Params: '(aVar: integer; aSrc: integer; aNum : integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SendRawCommand'; Location: 2; Params: '(aCmd : string; bRetry : boolean)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SendRemoteStr'; Location: 2; Params: '(aEvent : string; aRepeat : integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SendRemote'; Location: 2; Params: '(aEvent : Word; aRepeat : integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SendMessage'; Location: 2; Params: '(aMsg : integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SelectProgram'; Location: 2; Params: '(aProg : integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SelectDisplay'; Location: 2; Params: '(aSrc: integer; aNum : integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SetWatchHHMM'; Location: 2; Params: '(aHrs: integer; aMins : integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SetWatch'; Location: 2; Params: '(aTime: string)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'DownloadFirmware'; Location: 2; Params: '(aFile : string; bFast: boolean; bComp: boolean; bUnlock: boolean)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SetDatalog'; Location: 2; Params: '(aSize : integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'DatalogNext'; Location: 2; Params: '(aSrc: integer; aNum : integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'UploadPartialDatalog'; Location: 2; Params: '(aFrom: integer; aSize : integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'UploadDatalog'; Location: 2; Params: '(bVerbose : boolean)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Drive'; Location: 2; Params: '(aLeft: integer; aRight : integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'ClearTachoCounter'; Location: 2; Params: '(aMotorList : Byte)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'OnWait'; Location: 2; Params: '(aMotorList : Byte; aNum : integer; aTime : Byte)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'OnWaitDifferent'; Location: 2; Params: '(aMotorList : Byte; aNum0: integer; aNum1: integer; aNum2: integer; aTime : Byte)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'ScoutNum'; Location: 2; Params: '(aVal : integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Scout'; Location: 2; Params: '(bPower : boolean)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'CalibrateLightSensor'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SetFeedback'; Location: 2; Params: '(aSrc: integer; aVal : integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SetLightSensorUpperThreshold'; Location: 2; Params: '(src : TLSSource; val : TThresholdValue)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SetLightSensorLowerThreshold'; Location: 2; Params: '(src : TLSSource; val : TThresholdValue)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SetLightSensorHysteresis'; Location: 2; Params: '(src : TLSSource; val : TThresholdValue)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SetLightSensorBlinkTime'; Location: 2; Params: '(src : TLSSource; val : TThresholdValue)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SetTimerLimit'; Location: 2; Params: '(num : TTimerNumber; src : TTCSource; val : integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SetCounterLimit'; Location: 2; Params: '(num : TCounterNumber; src : TTCSource; val : integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'ScoutRules'; Location: 2; Params: '(motion : TScoutMotion; touch : TScoutTouch; light : TScoutLight; time : TScoutScale; fx : TScoutEffects)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'ScoutSound'; Location: 2; Params: '(bSoundEnable : boolean; bSoundOff : boolean; aNum : TSoundSetNumber)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SendVLL'; Location: 2; Params: '(aSrc: integer; aNum : integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SetLight'; Location: 2; Params: '(bOn : boolean)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'PollMemory'; Location: 2; Params: '(address : Integer; size : Integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SetGlobalOutput'; Location: 2; Params: '(motors : TMotorsNum; action : TGlobalOutAction)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SetGlobalDirection'; Location: 2; Params: '(motors : TMotorsNum; action : TGlobalDirAction)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SetMaxPower'; Location: 2; Params: '(motors : TMotorsNum; src: integer; num: integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'IncCounter'; Location: 2; Params: '(num : TCounterNumber)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'DecCounter'; Location: 2; Params: '(num : TCounterNumber)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'ClearCounter'; Location: 2; Params: '(num : TCounterNumber)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'ClearSound'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'UnmuteSound'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SendUARTData'; Location: 2; Params: '(start: integer; size: integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SetEvent'; Location: 2; Params: '(enum: integer; snum: integer; etype: integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'CalibrateEvent'; Location: 2; Params: '(enum: integer; upper: integer; lower: integer; hysteresis: integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'ClearAllEvents'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SetSourceValue'; Location: 2; Params: '(aDestSrc: Byte; aDestVal: Byte; aOrigSrc: Byte; aOrigVal: Smallint)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'MuteSound'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'ViewSourceValue'; Location: 2; Params: '(prec: integer; src: integer; value: integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'PollEEPROM'; Location: 2; Params: '(block: integer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTStartProgram'; Location: 2; Params: '(const filename : string)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTStopProgram'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTPlaySoundFile'; Location: 2; Params: '(const filename : string; bLoop : boolean)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'GetNXTOutputState'; Location: 2; Params: '(const port: byte; var power: integer; var mode: byte; var regmode: byte; var turnratio: integer; var runstate: byte; var tacholimit: cardinal; var tachocount: longint; var blocktachocount: longint; var rotationcount: longint)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SetNXTOutputState'; Location: 2; Params: '(const port: byte; const power: integer; const mode: byte; const regmode: byte; const turnratio: integer; const runstate: byte; const tacholimit: cardinal)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'GetNXTInputValues'; Location: 2; Params: '(const port: byte; var valid: boolean; var calibrated: boolean; var stype: byte; var smode: byte; var raw: word; var normalized: word; var scaled: smallint; var calvalue: smallint)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SetNXTInputMode'; Location: 2; Params: '(const port: byte; const stype: byte; const smode: byte)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'SetNXTInputMode'; Location: 2; Params: '(const port: byte; const stype: byte; const smode: byte)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTResetInputScaledValue'; Location: 2; Params: '(const port: byte)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTResetOutputPosition'; Location: 2; Params: '(const port : byte; const Relative : boolean)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTMessageWrite'; Location: 2; Params: '(const inbox : byte; const msg : string)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTKeepAlive'; Location: 2; Params: '(var time : cardinal; const chkResponse : boolean)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTLSGetStatus'; Location: 2; Params: '(port : byte; var bytesReady : byte; var lsstate : byte)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTGetCurrentProgramName'; Location: 2; Params: '(var name : string)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTGetButtonState'; Location: 2; Params: '(const idx : byte; const reset : boolean; var pressed : boolean; var count : byte)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTMessageRead'; Location: 2; Params: '(const remote: byte; const local: byte; const remove : boolean; var Msg : NXTMessage)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTSetPropDebugging'; Location: 2; Params: '(const debugging : boolean; const pauseClump : byte; const pausePC : Word)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTGetPropDebugging'; Location: 2; Params: '(var debugging : boolean; var pauseClump : byte; var pausePC : Word)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTSetVMState'; Location: 2; Params: '(const state : byte)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTSetVMStateEx'; Location: 2; Params: '(var state : byte; var clump : byte; var pc : word)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTGetVMState'; Location: 2; Params: '(var state : byte; var clump : byte; var pc : word)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTOpenRead'; Location: 2; Params: '(const filename : string; var handle : FantomHandle; var size : cardinal)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTOpenWrite'; Location: 2; Params: '(const filename : string; const size : cardinal; var handle : FantomHandle)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTRead'; Location: 2; Params: '(var handle : FantomHandle; var count : word; var buffer : NXTDataBuffer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTWrite'; Location: 2; Params: '(var handle : FantomHandle; const buffer : NXTDataBuffer; var count : word; const chkResponse : boolean)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTCloseFile'; Location: 2; Params: '(var handle : FantomHandle; const chkResponse : boolean)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTDeleteFile'; Location: 2; Params: '(var filename : string; const chkResponse : boolean)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTFindFirstFile'; Location: 2; Params: '(var filename : string; var IterHandle : FantomHandle; var filesize, availsize : cardinal)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTFindNextFile'; Location: 2; Params: '(var IterHandle : FantomHandle; var filename : string; var filesize, availsize : cardinal)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTFindClose'; Location: 2; Params: '(var IterHandle : FantomHandle)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTGetVersions'; Location: 2; Params: '(var protmin: byte; var protmaj: byte; var firmmin: byte; var firmmaj: byte)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTFirmwareVersion'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTInstalledFirmware'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTOpenWriteLinear'; Location: 2; Params: '(const filename : string; const size : cardinal; var handle : FantomHandle)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTOpenReadLinear'; Location: 2; Params: '(const filename : string; var handle : FantomHandle; var size : cardinal)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTOpenWriteData'; Location: 2; Params: '(const filename : string; const size : cardinal; var handle : FantomHandle)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTOpenAppendData'; Location: 2; Params: '(const filename : string; var size : cardinal; var handle : FantomHandle)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTCloseModuleHandle'; Location: 2; Params: '(var handle : FantomHandle; const chkResponse : boolean)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTBootCommand'; Location: 2; Params: '(const chkResponse : boolean)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTSetBrickName'; Location: 2; Params: '(const name: string; const chkResponse : boolean)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTGetBrickName'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTGetDeviceInfo'; Location: 2; Params: '(var name : string; var BTAddress : string; var BTSignal : Cardinal; var memFree : Cardinal)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTFreeMemory'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTDeleteUserFlash'; Location: 2; Params: '(const chkResponse : boolean)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTBTFactoryReset'; Location: 2; Params: '(const chkResponse : boolean)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTPollCommandLen'; Location: 2; Params: '(const bufNum : byte; var count : byte)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTPollCommand'; Location: 2; Params: '(const bufNum : byte; var count : byte; var buffer : NXTDataBuffer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTWriteIOMap'; Location: 2; Params: '(var ModID : Cardinal; const Offset : Word; var count : Word; const buffer : NXTDataBuffer; chkResponse : Boolean)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTReadIOMap'; Location: 2; Params: '(var ModID : Cardinal; const Offset : Word; var count : Word; var buffer : NXTDataBuffer)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTFindFirstModule'; Location: 2; Params: '(var ModName : string; var Handle : FantomHandle; var ModID: Cardinal; var ModSize: Cardinal; var IOMapSize : Word)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTFindNextModule'; Location: 2; Params: '(var Handle : FantomHandle; var ModName : string; var ModID: Cardinal; var ModSize: Cardinal; var IOMapSize : Word)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTRenameFile'; Location: 2; Params: '(const old: string; const new: string; const chkResponse : boolean)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTDownloadFile'; Location: 2; Params: '(const filename : string; const filetype : TNXTFileType)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTDownloadStream'; Location: 2; Params: '(aStream : TStream; const dest : string; const filetype : TNXTFileType)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTUploadFile'; Location: 2; Params: '(const filename : string; const dir : string)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTUploadFileToStream'; Location: 2; Params: '(const filename : string; aStream : TStream)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTListFiles'; Location: 2; Params: '(const searchPattern : string; Files : TStrings)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTListModules'; Location: 2; Params: '(const searchPattern : string; Modules : TStrings)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTListBricks'; Location: 2; Params: '(Bricks : TStrings)'; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTInitializeResourceNames'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTUpdateResourceNames'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTDefragmentFlash'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'EEPROM'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'EEPROMBlocks'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NXTLowSpeed'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'IsOpen'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'FastMode'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'UseBluetooth'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'BluetoothName'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'BluetoothSearchTimeout'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Quiet'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'BrickType'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'Port'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'PortName'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'NicePortName'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'FullPortName'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'BrickTypeName'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'RxTimeout'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'VerboseMode'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'AutoClose'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'DataLog'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'MemoryMap'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'MemoryData'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'TowerExistsSleep'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'LinkLog'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'RCXFirmwareChunkSize'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'DownloadWaitTime'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'OmitHeader'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'OnDownloadStart'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'OnDownloadDone'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'OnDownloadStatus'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'OnOpenStateChanged'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'OnGetVarInfoByID'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIFunc; Name: 'OnGetVarInfoByName'; Location: 2; Params: ''; Count: 1; Alpha: atNumeric),
(*

    (Kind: ckAPIConst; Name: 'kRCX_PingOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_MemMapOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_BatteryLevelOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_DeleteTasksOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_StopAllOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_PBTurnOffOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_DeleteSubsOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_ClearSound'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_ClearMsgOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_ExitAccessCtrlOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_ExitEventChkOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_LSCalibrateOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_MuteSoundOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_UnmuteSoundOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_PopStackEntryOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_UploadEepromOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_ClearTachoOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_OutputModeOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_IRModeOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_DriveOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_PlaySoundOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_DeleteTaskOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_StartTaskOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_StopTaskOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SelectProgramOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_ClearTimerOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_AutoOffOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_DeleteSubOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_ClearSensorOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_OutputDirOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_PlayToneVarOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_PollOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SetWatchOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_InputTypeOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_InputModeOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SetDatalogOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_DatalogOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_JumpOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SetLoopOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_CheckLoopOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SendMessageOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SendUARTDataOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_OnWaitOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_Remote'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_VLLOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_DecVarJmpLTZOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_DirectEventOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_OutputPowerOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_PlayToneOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_DisplayOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_WaitOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_OnWaitDifferentOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_PollMemoryOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_EnterAccessCtrlOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SetFeedbackOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SetEventOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_GOutputPowerOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_LSUpperThreshOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_LSLowerThreshOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_LSHysteresisOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_PushStackEntryOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_LSBlinkTimeOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_LDecVarJmpLTZOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_CalibrateEventOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SetVarOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SumVarOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SubVarOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_DivVarOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_MulVarOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SgnVarOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_AbsVarOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_AndVarOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_OrVarOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_UploadDatalogOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SEnterEventChkOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SetTimerLimitOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SetCounterOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SetSourceValueOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_UnlockOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_BeginTaskOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_BeginSubOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_DownloadOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_BootModeOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_BeginFirmwareOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SCheckDoOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_LCheckDoOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_UnlockFirmOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_LEnterEventChkOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_FindOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_ScoutRulesOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_ViewSourceValOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_ClearAllEventsOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_ClearRelTableOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_EndOfSubOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_GoSubOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SJumpOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SChkLoopCtrOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_ScoutOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SoundOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_GOutputModeOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_GOutputDirOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_LightOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_IncCounterOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_DecCounterOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_ClearCounterOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_PlaySysMoodOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SetPriorityOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_PlaySysSndVarOp'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_Message'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_OutputFloat'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_OutputOff'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_OutputOn'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_OutputBackward'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_OutputToggle'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_OutputForward'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_VMState_Idle'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_VMState_RunFree'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_VMState_Single'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_VMState_Pause'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_VMState_Reset'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_NoResponseMask'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DirectCmd'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_SystemCmd'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_CmdReply'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DirectCmdNoReply'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_SystemCmdNoReply'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_MaxBytes'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_NameMaxLen'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DCStartProgram'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DCStopProgram'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DCPlaySoundFile'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DCPlayTone'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DCSetOutputState'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DCSetInputMode'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DCGetOutputState'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DCGetInputValues'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DCResetInputScaledValue'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DCMessageWrite'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DCResetMotorPosition'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DCGetBatteryLevel'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DCStopSoundPlayback'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DCKeepAlive'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DCLSGetStatus'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DCLSWrite'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DCLSRead'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DCGetCurrentProgramName'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DCGetButtonState'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DCMessageRead'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DCDatalogRead'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DCDatalogSetTimes'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DCBTGetContactCount'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DCBTGetContactName'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DCBTGetConnectionCount'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DCBTGetConnectionName'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DCSetProperty'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DCGetProperty'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DCUpdateResetCount'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DCSetVMState'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DCGetVMState'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DCSetBreakpoints'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_DCGetBreakpoints'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_Property_BTOnOff'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_Property_SoundLevel'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_Property_SleepTimeout'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_Property_Debugging'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_SCOpenRead'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_SCOpenWrite'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_SCRead'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_SCWrite'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_SCClose'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_SCDelete'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_SCFindFirst'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_SCFindNext'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_SCGetVersions'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_SCOpenWriteLinear'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_SCOpenReadLinear'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_SCOpenWriteData'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_SCOpenAppendData'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_SCFindFirstModule'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_SCFindNextModule'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_SCCloseModuleHandle'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_SCIOMapRead'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_SCIOMapWrite'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_SCBootCommand'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_SCSetBrickName'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_SCGetBTAddress'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_SCGetDeviceInfo'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_SCDeleteUserFlash'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_SCPollCommandLen'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_SCPollCommand'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_SCRenameFile'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_SCBTFactoryReset'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_StatusSuccess'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_StatusNoMoreHandles'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_StatusNoSpace'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_StatusNoMoreFiles'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_StatusEOFExpected'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_StatusEOF'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_StatusNotLinearFile'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_StatusFileNotFound'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_StatusHandleClosed'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_StatusNoLinearSpace'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_StatusUndefinedErr'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_StatusFileIsBusy'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_StatusNoWriteBufs'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_StatusAppendNotPoss'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_StatusFileIsFull'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_StatusFileExists'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_StatusModuleNotFound'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_StatusOutOfBoundary'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_StatusIllegalFilname'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_StatusIllegalHandle'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'NXT_MODULE_COUNT'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_TT_Cmd'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_TT_Output'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_TT_Input'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_TT_Button'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_TT_Comm'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_TT_IOCtrl'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_TT_Led'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_TT_Sound'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_TT_Loader'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_TT_Display'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_TT_LowSpeed'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_TT_UI'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_PidLEGOGroup'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_ModuleCmd'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_ModuleOutput'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_ModuleInput'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_ModuleButton'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_ModuleComm'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_ModuleIOCtrl'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_ModuleLed'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_ModuleSound'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_ModuleLoader'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_ModuleDisplay'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_ModuleLowSpeed'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_ModuleUI'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_ModuleCmdName'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_ModuleOutputName'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_ModuleInputName'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_ModuleButtonName'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_ModuleCommName'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_ModuleIOCtrlName'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_ModuleLedName'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_ModuleSoundName'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_ModuleLoaderName'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_ModuleDisplayName'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_ModuleLowSpeedName'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kNXT_ModuleUIName'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'TNXTModule'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIType; Name: 'TRcxValueType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_VariableType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_TimerType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_ConstantType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_OutputStatusType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_RandomType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_TachCounterType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_TachSpeedType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_OutputCurrentType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_ProgramSlotType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_InputValueType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_InputTypeType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_InputModeType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_InputRawType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_InputBooleanType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_WatchType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_MessageType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_AGCType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_GlobalMotorStatusType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_ScoutRulesType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_ScoutLightParamsType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_ScoutTimerLimitType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SpybotStackType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SpybotTimerCtrlType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SpybotEepromType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_CounterType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_ScoutCounterLimitType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SpybotLEDType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_TaskEventsType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_ScoutEventFBType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_EventStateType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_TenMSTimerType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_ClickCounterType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_UpperThresholdType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_LowerThresholdType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_HysteresisType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_DurationType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SpybotTaskIDType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_UARTSetupType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_BatteryLevelType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_FirmwareVersionType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_IndirectVarType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_DatalogTypeIndirectType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_DatalogTypeDirectType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_DatalogValueIndirectType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_DatalogValueDirectType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_DatalogRawIndirectType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_DatalogRawDirectType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SpybotGameNotesType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SpybotRobotDistType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SpybotRobotDirType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SpybotRobotOrientType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SpybotRobotIDType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SpybotRobotTargetType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SpybotPingCtrlType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SpybotBeaconCtrlType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SpybotSoundCtrlType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_SpybotIndEepromType'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
	  (Kind: ckAPIConst; Name: 'kRCX_InputRaw'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
	  (Kind: ckAPIConst; Name: 'kRCX_InputBoolean'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
	  (Kind: ckAPIConst; Name: 'kRCX_InputEdgeCounter'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
	  (Kind: ckAPIConst; Name: 'kRCX_InputPeriodicCounter'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
	  (Kind: ckAPIConst; Name: 'kRCX_InputPercentage'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
	  (Kind: ckAPIConst; Name: 'kRCX_InputCelcius'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
	  (Kind: ckAPIConst; Name: 'kRCX_InputFahrenheit'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
	  (Kind: ckAPIConst; Name: 'kRCX_InputAngle'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_OK'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_OpenSerialError'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_IREchoError'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_ReplyError'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_RequestError'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_FileError'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_FormatError'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_AbortError'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_MemFullError'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_PipeModeError'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
    (Kind: ckAPIConst; Name: 'kRCX_LastError'; Location: 4; Params: ''; Count: 1; Alpha: atNumeric),
*)

    (Kind: ckAPIFunc; Name: '**XYZZY**'; Location: 0; Params: ''; Count: 0; Alpha: atNumeric)
  );

implementation

end.