unit uPSI_brick_common;
{
This file has been generated by UnitParser v0.7, written by M. Knight
and updated by NP. v/d Spek and George Birbilis. 
Source Code from Carlo Kok has been used to implement various sections of
UnitParser. Components of ROPS are used in the construction of UnitParser,
code implementing the class wrapper is taken from Carlo Kok's conv utility

}
interface
 
uses
   SysUtils
  ,Classes
  ,uPSComponent
  ,uPSRuntime
  ,uPSCompiler
  ;
 
type 
(*----------------------------------------------------------------------------*)
  TPSImport_brick_common = class(TPSPlugin)
  protected
    procedure CompileImport1(CompExec: TPSScript); override;
    procedure ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter); override;
  end;
 
 
{ compile-time registration functions }
procedure SIRegister_brick_common(CL: TPSPascalCompiler);

{ run-time registration functions }
procedure RIRegister_brick_common_Routines(S: TPSExec);

procedure Register;

implementation


uses
   uSpirit
  ,brick_common
  ;
 
 
procedure Register;
begin
  RegisterComponents('Pascal Script', [TPSImport_brick_common]);
end;

(* === compile-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure SIRegister_brick_common(CL: TPSPascalCompiler);
begin
 CL.AddDelphiFunction('Function BrickComm : TBrickComm');
 CL.AddDelphiFunction('Procedure ReleaseBrickComm');
 CL.AddDelphiFunction('Procedure CreateInitFile');
end;

(* === run-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure RIRegister_brick_common_Routines(S: TPSExec);
begin
 S.RegisterDelphiFunction(@BrickComm, 'BrickComm', cdRegister);
 S.RegisterDelphiFunction(@ReleaseBrickComm, 'ReleaseBrickComm', cdRegister);
 S.RegisterDelphiFunction(@CreateInitFile, 'CreateInitFile', cdRegister);
end;

 
 
{ TPSImport_brick_common }
(*----------------------------------------------------------------------------*)
procedure TPSImport_brick_common.CompileImport1(CompExec: TPSScript);
begin
  SIRegister_brick_common(CompExec.Comp);
end;
(*----------------------------------------------------------------------------*)
procedure TPSImport_brick_common.ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter);
begin
//  RIRegister_brick_common(ri);
  RIRegister_brick_common_Routines(CompExec.Exec); // comment it if no routines
end;
(*----------------------------------------------------------------------------*)
 
 
end.
