// Do not edit. This file is machine generated by the Resource DLL Wizard.

library BricxCC_10_49;

{ITE} {LCID:00000409:0000040A} {}
{ITE} {DFMFileType} {Piano.dfm}
{ITE} {RCFileType} {ToolbarBackground.rc}
{ITE} {RCFileType} {NXTSound.rc}
{ITE} {RCFileType} {VistaManifest.rc}
{ITE} {<unknown>} {macro_img.res}

{$R 'Piano.dfm'}
{$R 'ToolbarBackground.res' 'ToolbarBackground.rc'}
{$R 'NXTSound.res' 'NXTSound.rc'}
{$R 'VistaManifest.res' 'VistaManifest.rc'}

{$E ESP}

begin
end.