// Do not edit. This file is machine generated by the Resource DLL Wizard.

library BricxCC;

{$R *.RES}
{ITE} {LCID:00000409:0000040A} {}
{ITE} {DFMFileType} {About.dfm}
{ITE} {DFMFileType} {CodeTemplates.dfm}
{ITE} {DFMFileType} {CodeUnit.dfm}
{ITE} {DFMFileType} {ConstructUnit.dfm}
{ITE} {DFMFileType} {Controller.dfm}
{ITE} {DFMFileType} {DataAnalysis.dfm}
{ITE} {DFMFileType} {DatalogUnit.dfm}
{ITE} {DFMFileType} {Diagnose.dfm}
{ITE} {DFMFileType} {DPageSetup.dfm}
{ITE} {DFMFileType} {DTestPrintPreview.dfm}
{ITE} {DFMFileType} {EditCodeTemplate.dfm}
{ITE} {DFMFileType} {Editor.dfm}
{ITE} {DFMFileType} {GotoLine.dfm}
{ITE} {DFMFileType} {GX_ProcedureList.dfm}
{ITE} {DFMFileType} {JoystickUnit.dfm}
{ITE} {DFMFileType} {MainUnit.dfm}
{ITE} {DFMFileType} {MemoryUnit.dfm}
{ITE} {DFMFileType} {MessageUnit.dfm}
{ITE} {DFMFileType} {Piano.dfm}
{ITE} {DFMFileType} {Preferences.dfm}
{ITE} {DFMFileType} {PuzzleUnit.dfm}
{ITE} {DFMFileType} {RemoteUnit.dfm}
{ITE} {DFMFileType} {SearchRCX.dfm}
{ITE} {DFMFileType} {Transdlg.dfm}
{ITE} {DFMFileType} {Transfer.dfm}
{ITE} {DFMFileType} {uChartConfig.dfm}
{ITE} {DFMFileType} {uChartExport.dfm}
{ITE} {DFMFileType} {uCodeExplorer.dfm}
{ITE} {DFMFileType} {uEEPROM.dfm}
{ITE} {DFMFileType} {uExplorerOptions.dfm}
{ITE} {DFMFileType} {uExtensionDlg.dfm}
{ITE} {DFMFileType} {uForthConsole.dfm}
{ITE} {DFMFileType} {uHEXViewer.dfm}
{ITE} {DFMFileType} {uMacroEditor.dfm}
{ITE} {DFMFileType} {uMacroForm.dfm}
{ITE} {DFMFileType} {uMIDIConversion.dfm}
{ITE} {DFMFileType} {uNewWatch.dfm}
{ITE} {DFMFileType} {Unlock.dfm}
{ITE} {DFMFileType} {uNXTController.dfm}
{ITE} {DFMFileType} {uNXTExplorer.dfm}
{ITE} {DFMFileType} {uNXTImage.dfm}
{ITE} {DFMFileType} {uProjectManager.dfm}
{ITE} {DFMFileType} {uPromptSeries.dfm}
{ITE} {DFMFileType} {uSeriesConfig.dfm}
{ITE} {DFMFileType} {uSetLNPAddress.dfm}
{ITE} {DFMFileType} {uSetValues.dfm}
{ITE} {DFMFileType} {uWav2RSO.dfm}
{ITE} {DFMFileType} {uWindowList.dfm}
{ITE} {DFMFileType} {Watch.dfm}
{ITE} {RCFileType} {NXTSound.rc}
{ITE} {RCFileType} {ToolbarBackground.rc}
{ITE} {RCFileType} {VistaManifest.rc}
{ITE} {RCFileType} {BricxCC_DRC.rc}

{$R 'About.dfm' AboutBox:TForm}
{$R 'CodeTemplates.dfm' frmCodeTemplates:TForm}
{$R 'CodeUnit.dfm' CodeForm:TForm}
{$R 'ConstructUnit.dfm' ConstructForm:TForm}
{$R 'Controller.dfm' DirectForm:TForm}
{$R 'DataAnalysis.dfm' frmDataAnalysis:TForm}
{$R 'DatalogUnit.dfm' DatalogForm:TForm}
{$R 'Diagnose.dfm' DiagForm:TForm}
{$R 'DPageSetup.dfm' PageSetupDlg:TForm}
{$R 'DTestPrintPreview.dfm' TestPrintPreviewDlg:TForm}
{$R 'EditCodeTemplate.dfm' frmEditCodeTemplate:TForm}
{$R 'Editor.dfm' EditorForm:TForm}
{$R 'GotoLine.dfm' GotoForm:TForm}
{$R 'GX_ProcedureList.dfm' fmProcedureList:TForm}
{$R 'JoystickUnit.dfm' JoystickForm:TForm}
{$R 'MainUnit.dfm' MainForm:TForm}
{$R 'MemoryUnit.dfm' MemoryForm:TForm}
{$R 'MessageUnit.dfm' MessageForm:TForm}
{$R 'Piano.dfm' PianoForm:TForm}
{$R 'Preferences.dfm' PrefForm:TForm}
{$R 'PuzzleUnit.dfm' PuzzleForm:TForm}
{$R 'RemoteUnit.dfm' RemoteForm:TForm}
{$R 'SearchRCX.dfm' SearchRCXForm:TForm}
{$R 'Transdlg.dfm' frmTransEdit:TForm}
{$R 'Transfer.dfm' frmTransferDlg:TForm}
{$R 'uChartConfig.dfm' frmChartConfig:TForm}
{$R 'uChartExport.dfm' frmChartExport:TForm}
{$R 'uCodeExplorer.dfm' frmCodeExplorer:TForm}
{$R 'uEEPROM.dfm' frmSpybotEEPROM:TForm}
{$R 'uExplorerOptions.dfm' frmExplorerOptions:TForm}
{$R 'uExtensionDlg.dfm' frmExtensionDlg:TForm}
{$R 'uForthConsole.dfm' frmForthConsole:TForm}
{$R 'uHEXViewer.dfm' frmHexView:TForm}
{$R 'uMacroEditor.dfm' frmMacroEditor:TForm}
{$R 'uMacroForm.dfm' frmMacroManager:TForm}
{$R 'uMIDIConversion.dfm' frmMIDIConversion:TForm}
{$R 'uNewWatch.dfm' frmNewWatch:TForm}
{$R 'Unlock.dfm' UnlockForm:TForm}
{$R 'uNXTController.dfm' frmNXTController:TForm}
{$R 'uNXTExplorer.dfm' frmNXTExplorer:TForm}
{$R 'uNXTImage.dfm' frmNXTImage:TForm}
{$R 'uProjectManager.dfm' frmProjectManager:TForm}
{$R 'uPromptSeries.dfm' frmSeriesPrompt:TForm}
{$R 'uSeriesConfig.dfm' frmSeriesConfig:TForm}
{$R 'uSetLNPAddress.dfm' frmSetLNPAddress:TForm}
{$R 'uSetValues.dfm' frmSetValues:TForm}
{$R 'uWav2RSO.dfm' frmWave2RSO:TForm}
{$R 'uWindowList.dfm' frmWindowList:TForm}
{$R 'Watch.dfm' WatchForm:TForm}
{$R 'NXTSound.res' 'NXTSound.rc'}
{$R 'ToolbarBackground.res' 'ToolbarBackground.rc'}
{$R 'VistaManifest.res' 'VistaManifest.rc'}
{$R 'BricxCC_DRC.res' 'BricxCC_DRC.rc'}

{$E ESP}

begin
end.