// Do not edit. This file is machine generated by the Resource DLL Wizard.

library BricxCC_9_49;

{ITE} {LCID:00000409:00000419} {}
{ITE} {DFMFileType} {SearchRCX.dfm}
{ITE} {RCFileType} {ToolbarBackground.rc}
{ITE} {RCFileType} {NXTSound.rc}
{ITE} {RCFileType} {VistaManifest.rc}
{ITE} {<unknown>} {macro_img.res}

{$R 'SearchRCX.dfm'}
{$R 'ToolbarBackground.res' 'ToolbarBackground.rc'}
{$R 'NXTSound.res' 'NXTSound.rc'}
{$R 'VistaManifest.res' 'VistaManifest.rc'}

{$E RUS}

begin
end.