// Do not edit. This file is machine generated by the Resource DLL Wizard.

library BricxCC_30_49;

{ITE} {LCID:00000409:0000040C} {}
{ITE} {DFMFileType} {uCodeExplorer.dfm}
{ITE} {RCFileType} {ToolbarBackground.rc}
{ITE} {RCFileType} {NXTSound.rc}
{ITE} {RCFileType} {VistaManifest.rc}
{ITE} {<unknown>} {macro_img.res}

{$R 'uCodeExplorer.dfm'}
{$R 'ToolbarBackground.res' 'ToolbarBackground.rc'}
{$R 'NXTSound.res' 'NXTSound.rc'}
{$R 'VistaManifest.res' 'VistaManifest.rc'}

{$E FRA}

begin
end.